version: '3.8'

services:
  optimizer:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - jupyter_data:/home/optimizer/.jupyter
    environment:
      - PYTHONPATH=/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root

  benchmark:
    build: .
    volumes:
      - .:/app
      - ./results:/app/results
    environment:
      - PYTHONPATH=/app
    command: python benchmarks/scipy_comparison.py
    profiles:
      - benchmark

volumes:
  jupyter_data:
